Added tab bar, and made changes to improve the code
wolox-training/fr-swift pull request #4
Opened 2018-03-14 15:24 UTC by florenciarosental

## Summary ##

**Trello card**: https://trello.com/c/xNLDtBdt/15-tab-bar

**A brief description of the pull request**

- Added TabBarController, to manage the different tabs from the bottom. 
- Created controllers for each one of those tabs.
- Added ViewModel for books, to handle the download of images instead of doing it in the controller.
- Edited the view of the books cells, and added an extension to bing the data in the cell from the class.
- Created UIImageExtensions file to contain images.
- Added Localization to make the app support other languages (in case it was needed).
- Edited the LibraryViewController to hangle BookViewModels instead of books.

## Screenshots ##

### iPhone 6+/7+

![screen shot 2018-03-14 at 12 17 03](https://user-images.githubusercontent.com/36637487/37411513-bbae27ea-2781-11e8-95bb-cb5b8defd459.png)

## Screencast ##

![tab bar](https://user-images.githubusercontent.com/36637487/37411879-94749b72-2782-11e8-8f96-7b4e91d70226.gif)

2018-03-14 20:44 UTC, pablog commented
@florenciarosental before looking at the code a couple of comments:

1- Don't forget to upload a screenshot for EVERY different screen size. They're useful for validating the screen renders as expected, which should happen in every screen size, not only in one.

2- Make a different commit (and ideally a different pull request) for each different change. I know this is kind of hard when the project begins, but try to make the practice. In this case you may have made a commit for each of the comments you made in the PR description (great you identified the different changes, next time just make a commit for each).

3- Be more detailed with the commit name. They're important if we need to find a certain change in the past, and the name of the commit may be useful for this. Let's try to avoid comments like "and made changes to improve the code". Instead, in my opinion the descriptions you used in the PR description perfectly fit for a commit name.

Good improvements this week! 👍

2018-03-15 13:52 UTC, florenciarosental commented
@pablog Great, thanks! I will be remembering those things for the following commits and the next PR.

2018-03-15 16:35 UTC, aducret requested changes

2018-03-15 16:35 UTC, aducret commented on WBooks/Views/Book/BookViewModel.swift
> +import ReactiveSwift
I think you are not using `ReactiveSwift` here.

2018-03-15 16:35 UTC, aducret commented on WBooks/Views/Library/Cell_TableView/BookCellView.swift
> -    func setCornerRadius(){
are you doing this in interface builder?

2018-03-15 16:35 UTC, aducret commented on WBooks/Views/Library/LibraryViewModel.swift
> +    let books = MutableProperty<[BookViewModel]>([])
In this case you should use a `Property` instead a `MutableProperty`. You can create a `Property` using a `MutableProperty` some thing like that: 

``` swift code
internal final class LibraryViewModel {
   private let _book = MutableProperty<[BookViewModel]>([])
   let book: Property<[BookViewModel]>
   init() {
     book = Property(_book)
    } 
}
```
This is because if you use a `MutableProperty` an external object can modify the value of the mutable property but a `Property` is "immutable" only can change its values from the given MutableProperty or a Signal/Producer

2018-03-15 16:35 UTC, aducret commented on WBooks/Views/Library/LibraryViewModel.swift
> +        _libraryRepository.fetchBooks().startWithResult { [unowned self] result in
Remember that you can use `<~` to bind a `MutableProperty` to a `SignalProducer` (With the same type of value and without errors, to avoid error you can use `liftError`). Try to update it your self but any question or doubt just ask me.

2018-03-15 16:35 UTC, aducret commented on WBooks/TabBar/TabBarController.swift
> +    }
Add extra blank line between `}}`

2018-03-15 16:35 UTC, aducret commented on WBooks/TabBar/TabBarController.swift
> +    }
Add extra blank line between `}}`

2018-03-15 16:35 UTC, aducret commented on WBooks/Views/Library/LibraryViewController.swift
> +        let viewModel = _viewModel.books.value[indexPath.row] //esto va a ser un book viewmodel
Remove comment and remember to do comments in english.

2018-03-15 16:49 UTC, florenciarosental commented on WBooks/Views/Library/Cell_TableView/BookCellView.swift
> -    func setCornerRadius(){
Yes, Pol told me to move it there.

2018-03-15 18:36 UTC, aducret approved these changes

2018-03-15 19:32 UTC, merged